spring:
  profiles:
    active: dev
  application:
    name: auth-client
  boot:
    admin:
      client:
        url: "http://192.168.10.1:8091"
        instance:
          prefer-ip: true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.130:8848
  feign:
    compression:
      request:
        enabled: true
        mime-types: text/xml,application/xml,application/json
        min-request-size: 2048
      response:
        enabled: true
    hystrix:
      enabled: true

oauth2:
  base-url: http://localhost:8510/uas

security:
  oauth2:
    client:
      client-id: auth-client
      client-secret: auth-client
      user-authorization-uri: ${oauth2.base-url}/oauth/authorize
      access-token-uri: ${oauth2.base-url}/oauth/token
      pre-established-redirect-uri:
    resource:
      user-info-uri: ${oauth2.base-url}/user/me
      token-info-uri: ${oauth2.base-url}/oauth/check_token
      jwt:
        key-uri: ${oauth2.base-url}/oauth/token_key


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always