spring:
  profiles:
    active: dev
  feign:
    compression:
      request:
        enabled: true
        mime-types: text/xml,application/xml,application/json
        min-request-size: 2048
      response:
        enabled: true
    hystrix:
      enabled: true

security:
  oauth2:
    client:
      client-id: auth-client
      client-secret: auth-client
      user-authorization-uri: http://localhost:8510/uas/oauth/authorize
      access-token-uri: http://localhost:8510/uas/oauth/token
      # 加上grant-type 采用默认配置 会出现oauth2ClientContext 重复定义问题
      # grant-type: client_credentials
    resource:
      user-info-uri: http://localhost:8510/uas/api/userInfo
      # token-info-uri: http://localhost:8510/uas/oauth/check_token
      jwt:
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqUTFy1EKxaN2s26x4Bex
          RiTUEddheIVLtCZIO8oVvifHcED5vWtNWYD5aeENz0MLBULeY41ACJfSiMp25+2/
          XnC4i6VoE1+UhQDUVI6f+1K0TifOg4YYlUOw/t+7Pd4X38nbqoJDa56l2XJ6mItV
          p2BbeApQiMH+Ren6h728bSHwyH2jpsGUrLnluAf2QZKmctPhs1s2N+Dy6mBLG3Kt
          CL8GXFceocAMqCRchRFMnu+y6EX8JYU4ayppT1lMpy20j7pxVvq72LRTt87Pdjzu
          iOxdo2add16gWqwW71BNEcIyOhUy+y2os3ZF4I1m2OpwI3ATG3H3LDt/0YPeCJ/s
          3QIDAQAB
          -----END PUBLIC KEY-----



management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always