spring:
  profiles:
    active: dev
  security:
    oauth2:
      client:
        registration:
          uas:
            client-id: auth-client
            client-secret: auth-client
            client-name: eboot
            #client-authentication-method: basic
            authorization-grant-type: authorization_code
            redirect-uri: http://192.168.10.1:8530/login/oauth2/code/uas
            provider: uas
        provider:
            uas:
              authorization-uri: http://192.168.10.1:8510/uas/oauth/authorize
              token-uri: http://192.168.10.1:8510/uas/oauth/token
              user-info-uri: http://192.168.10.1:8510/uas/api/userInfo
              user-info-authentication-method: header
              jwk-set-uri: http://192.168.10.1:8510/uas/oauth/token_keys
              user-name-attribute: username



management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always