spring:
  profiles:
    active: dev
  application:
    name: auth-resource
  boot:
    admin:
      client:
        url: "http://192.168.10.1:8091"
        instance:
          prefer-ip: true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.130:8848

oauth2:
  base-url: http://localhost:8510/uas

security:
  oauth2:
    resource:
      token-info-uri: ${oauth2.base-url}/oauth/check_token
      jwt:
        key-uri: ${oauth2.base-url}/oauth/token_key


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always